name: Boilerplate
description: Runs boilerplate commands
runs:
  using: composite
  steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - uses: actions/cache@v2
      # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      id: yarn-cache
      with:
        path: |
          ./.yarn/cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn install
      shell: bash
    - run: yarn clean
      shell: bash
