FROM rust:1.98.0-slim

RUN rustup target add x86_64-unknown-linux-musl
RUN apt-get update && apt-get install -y musl-tools
RUN cargo install cargo-watch

WORKDIR /app

COPY . .
COPY showcase.json /etc/showcase/showcase.json

CMD ["cargo", "watch", "-x", "run"]
